#!/usr/bin/env python3
"""Regenerate data.js from the JSON files in data/.

Run this after editing any data/*.json file:
    python3 build-data.py

The app loads data.js via a <script> tag, which works from file://
(no web server needed), unlike fetch() of JSON files.
"""
import json
from pathlib import Path

ROOT = Path(__file__).parent
DATA_DIR = ROOT / "data"

bundle = {}
for name in ["planets", "signs", "houses", "concepts"]:
    with open(DATA_DIR / f"{name}.json", encoding="utf-8") as f:
        bundle[name] = json.load(f)

out = "// GENERATED by build-data.py — edit data/*.json instead, then re-run the script.\n"
out += "window.APP_DATA = " + json.dumps(bundle, ensure_ascii=False, indent=2) + ";\n"

with open(ROOT / "data.js", "w", encoding="utf-8") as f:
    f.write(out)

counts = {k: len(v) for k, v in bundle.items()}
print(f"data.js written: {counts}")
