// GENERATED by build-data.py — edit data/*.json instead, then re-run the script.
window.APP_DATA = {
  "planets": [
    {
      "id": "sun",
      "name": "Sun",
      "sanskritName": "Surya",
      "essence": "Authority",
      "naturalRelationships": {
        "friends": [
          "Moon",
          "Mars",
          "Jupiter"
        ],
        "enemies": [
          "Venus",
          "Saturn"
        ],
        "neutrals": [
          "Mercury"
        ]
      },
      "primarySignifications": [
        "Soul",
        "Father",
        "Authority",
        "Government",
        "Vitality"
      ],
      "represents": [
        "Soul (Ātman)",
        "Father",
        "Authority",
        "Government",
        "Kings and rulers",
        "Leadership",
        "Self-esteem",
        "Fame",
        "Honor",
        "Vitality",
        "Bones",
        "Eyes (especially right eye)",
        "Heart"
      ],
      "psychologicalQualities": [
        "Confidence",
        "Independence",
        "Dignity",
        "Responsibility",
        "Will power",
        "Leadership"
      ],
      "professions": [
        "Government",
        "Administration",
        "Politics",
        "Medicine",
        "Executive positions"
      ]
    },
    {
      "id": "moon",
      "name": "Moon",
      "sanskritName": "Chandra",
      "essence": "Mind",
      "naturalRelationships": {
        "friends": [
          "Sun",
          "Mercury"
        ],
        "enemies": [],
        "neutrals": [
          "Mars",
          "Jupiter",
          "Venus",
          "Saturn"
        ]
      },
      "primarySignifications": [
        "Mind",
        "Mother",
        "Emotions",
        "Nourishment"
      ],
      "represents": [
        "Mind (Manas)",
        "Mother",
        "Emotions",
        "Public popularity",
        "Nourishment",
        "Home",
        "Fluids",
        "Travel",
        "Memory",
        "Left eye",
        "Blood plasma"
      ],
      "psychologicalQualities": [
        "Compassion",
        "Sensitivity",
        "Adaptability",
        "Caring nature"
      ],
      "professions": [
        "Hospitality",
        "Nursing",
        "Public relations",
        "Food industry",
        "Shipping"
      ]
    },
    {
      "id": "mars",
      "name": "Mars",
      "sanskritName": "Mangala",
      "essence": "Action",
      "naturalRelationships": {
        "friends": [
          "Sun",
          "Moon",
          "Jupiter"
        ],
        "enemies": [
          "Mercury"
        ],
        "neutrals": [
          "Venus",
          "Saturn"
        ]
      },
      "primarySignifications": [
        "Courage",
        "Energy",
        "Siblings",
        "Property",
        "Warfare"
      ],
      "represents": [
        "Courage",
        "Brothers",
        "Soldiers",
        "Weapons",
        "Land",
        "Property",
        "Engineering",
        "Surgery",
        "Fire",
        "Blood",
        "Muscles"
      ],
      "psychologicalQualities": [
        "Initiative",
        "Aggression",
        "Confidence",
        "Determination"
      ],
      "professions": [
        "Military",
        "Police",
        "Surgery",
        "Engineering",
        "Athletics"
      ]
    },
    {
      "id": "mercury",
      "name": "Mercury",
      "sanskritName": "Budha",
      "essence": "Intellect",
      "naturalRelationships": {
        "friends": [
          "Sun",
          "Venus"
        ],
        "enemies": [
          "Moon"
        ],
        "neutrals": [
          "Mars",
          "Jupiter",
          "Saturn"
        ]
      },
      "primarySignifications": [
        "Intelligence",
        "Speech",
        "Learning",
        "Commerce"
      ],
      "represents": [
        "Intelligence",
        "Logic",
        "Speech",
        "Mathematics",
        "Writing",
        "Commerce",
        "Communication",
        "Business",
        "Education",
        "Youth",
        "Skin",
        "Nervous system"
      ],
      "psychologicalQualities": [
        "Curiosity",
        "Adaptability",
        "Analytical thinking",
        "Humor"
      ],
      "professions": [
        "Teaching",
        "Accounting",
        "IT",
        "Journalism",
        "Banking",
        "Marketing"
      ]
    },
    {
      "id": "jupiter",
      "name": "Jupiter",
      "sanskritName": "Guru",
      "essence": "Wisdom",
      "naturalRelationships": {
        "friends": [
          "Sun",
          "Moon",
          "Mars"
        ],
        "enemies": [
          "Mercury",
          "Venus"
        ],
        "neutrals": [
          "Saturn"
        ]
      },
      "primarySignifications": [
        "Wisdom",
        "Dharma",
        "Children",
        "Wealth",
        "Guru"
      ],
      "represents": [
        "Wisdom",
        "Dharma",
        "Religion",
        "Teachers",
        "Children",
        "Wealth",
        "Prosperity",
        "Justice",
        "Charity",
        "Sacred knowledge",
        "Liver",
        "Fat"
      ],
      "psychologicalQualities": [
        "Optimism",
        "Faith",
        "Generosity",
        "Ethics"
      ],
      "professions": [
        "Teacher",
        "Judge",
        "Priest",
        "Professor",
        "Financial advisor",
        "Counselor"
      ]
    },
    {
      "id": "venus",
      "name": "Venus",
      "sanskritName": "Shukra",
      "essence": "Love",
      "naturalRelationships": {
        "friends": [
          "Mercury",
          "Saturn"
        ],
        "enemies": [
          "Sun",
          "Moon"
        ],
        "neutrals": [
          "Mars",
          "Jupiter"
        ]
      },
      "primarySignifications": [
        "Marriage",
        "Spouse",
        "Luxury",
        "Arts",
        "Happiness"
      ],
      "represents": [
        "Wife (in a man's chart)",
        "Marriage",
        "Romance",
        "Love",
        "Beauty",
        "Luxury",
        "Music",
        "Fine arts",
        "Vehicles",
        "Jewelry",
        "Comfort",
        "Reproductive organs"
      ],
      "psychologicalQualities": [
        "Diplomacy",
        "Charm",
        "Refinement",
        "Appreciation of beauty"
      ],
      "professions": [
        "Artist",
        "Musician",
        "Fashion",
        "Designer",
        "Hospitality",
        "Entertainment"
      ]
    },
    {
      "id": "saturn",
      "name": "Saturn",
      "sanskritName": "Shani",
      "essence": "Discipline",
      "naturalRelationships": {
        "friends": [
          "Mercury",
          "Venus"
        ],
        "enemies": [
          "Sun",
          "Moon",
          "Mars"
        ],
        "neutrals": [
          "Jupiter"
        ]
      },
      "primarySignifications": [
        "Work",
        "Discipline",
        "Longevity",
        "Suffering",
        "Service"
      ],
      "represents": [
        "Longevity",
        "Hard work",
        "Labor",
        "Poverty",
        "Delays",
        "Discipline",
        "Karma",
        "Service",
        "Agriculture",
        "Old age",
        "Chronic diseases",
        "Teeth",
        "Legs"
      ],
      "psychologicalQualities": [
        "Patience",
        "Endurance",
        "Responsibility",
        "Humility"
      ],
      "professions": [
        "Engineering",
        "Mining",
        "Agriculture",
        "Manufacturing",
        "Labor administration",
        "Judiciary"
      ]
    },
    {
      "id": "rahu",
      "name": "Rahu",
      "sanskritName": "Rahu",
      "essence": "Ambition",
      "primarySignifications": [
        "Ambition",
        "Foreign influences",
        "Innovation",
        "Obsession"
      ],
      "represents": [
        "Foreign countries",
        "Foreign cultures",
        "Technology",
        "Aviation",
        "Politics",
        "Mass influence",
        "Obsession",
        "Ambition",
        "Illusion",
        "Innovation",
        "Sudden rise",
        "Unconventional paths"
      ],
      "psychologicalQualities": [
        "Curiosity",
        "Desire",
        "Risk-taking",
        "Nonconformity"
      ],
      "professions": [
        "Technology",
        "Artificial intelligence",
        "Foreign trade",
        "Politics",
        "Film",
        "Media",
        "Aviation"
      ]
    },
    {
      "id": "ketu",
      "name": "Ketu",
      "sanskritName": "Ketu",
      "essence": "Liberation",
      "primarySignifications": [
        "Spirituality",
        "Detachment",
        "Liberation",
        "Intuition"
      ],
      "represents": [
        "Moksha",
        "Renunciation",
        "Spirituality",
        "Intuition",
        "Mysticism",
        "Detachment",
        "Research",
        "Past-life karmas",
        "Mathematics",
        "Hidden knowledge"
      ],
      "psychologicalQualities": [
        "Detachment",
        "Insight",
        "Penetrating analysis",
        "Independence"
      ],
      "professions": [
        "Spiritual teacher",
        "Research scientist",
        "Astrologer",
        "Philosopher",
        "Investigator"
      ]
    }
  ],
  "signs": [
    {
      "id": "aries",
      "name": "Aries",
      "sanskritName": "Mesha",
      "number": 1,
      "ruler": "Mars",
      "element": "Fire",
      "modality": "Movable",
      "purushartha": "Dharma",
      "gender": "Odd (Masculine)",
      "nature": "Active",
      "characteristics": [
        "Courageous",
        "Independent",
        "Energetic",
        "Competitive",
        "Honest and direct",
        "Leadership ability",
        "Quick decision-maker"
      ],
      "strengths": [
        "Initiative",
        "Confidence",
        "Bravery"
      ],
      "weaknesses": [
        "Anger",
        "Impatience",
        "Impulsiveness"
      ]
    },
    {
      "id": "taurus",
      "name": "Taurus",
      "sanskritName": "Vrishabha",
      "number": 2,
      "ruler": "Venus",
      "element": "Earth",
      "modality": "Fixed",
      "purushartha": "Artha",
      "gender": "Even (Feminine)",
      "nature": "Stable",
      "characteristics": [
        "Patient",
        "Stable",
        "Practical",
        "Wealth-oriented",
        "Appreciates beauty and comfort",
        "Loyal"
      ],
      "strengths": [
        "Endurance",
        "Reliability",
        "Financial sense"
      ],
      "weaknesses": [
        "Stubbornness",
        "Possessiveness",
        "Resistance to change"
      ]
    },
    {
      "id": "gemini",
      "name": "Gemini",
      "sanskritName": "Mithuna",
      "number": 3,
      "ruler": "Mercury",
      "element": "Air",
      "modality": "Dual",
      "purushartha": "Kāma",
      "gender": "Odd (Masculine)",
      "nature": "Adaptable",
      "characteristics": [
        "Intelligent",
        "Curious",
        "Communicative",
        "Versatile",
        "Adaptable",
        "Social"
      ],
      "strengths": [
        "Learning",
        "Writing",
        "Networking"
      ],
      "weaknesses": [
        "Restlessness",
        "Indecision",
        "Inconsistency"
      ]
    },
    {
      "id": "cancer",
      "name": "Cancer",
      "sanskritName": "Karka",
      "number": 4,
      "ruler": "Moon",
      "element": "Water",
      "modality": "Movable",
      "purushartha": "Moksha",
      "gender": "Even (Feminine)",
      "nature": "Emotional",
      "characteristics": [
        "Caring",
        "Emotional",
        "Protective",
        "Intuitive",
        "Family-oriented"
      ],
      "strengths": [
        "Compassion",
        "Memory",
        "Nurturing ability"
      ],
      "weaknesses": [
        "Mood swings",
        "Emotional dependence",
        "Oversensitivity"
      ]
    },
    {
      "id": "leo",
      "name": "Leo",
      "sanskritName": "Simha",
      "number": 5,
      "ruler": "Sun",
      "element": "Fire",
      "modality": "Fixed",
      "purushartha": "Dharma",
      "gender": "Odd (Masculine)",
      "nature": "Royal",
      "characteristics": [
        "Noble",
        "Confident",
        "Charismatic",
        "Generous",
        "Leadership qualities"
      ],
      "strengths": [
        "Authority",
        "Courage",
        "Creativity"
      ],
      "weaknesses": [
        "Pride",
        "Ego",
        "Dominance"
      ]
    },
    {
      "id": "virgo",
      "name": "Virgo",
      "sanskritName": "Kanya",
      "number": 6,
      "ruler": "Mercury",
      "element": "Earth",
      "modality": "Dual",
      "purushartha": "Artha",
      "gender": "Even (Feminine)",
      "nature": "Analytical",
      "characteristics": [
        "Analytical",
        "Organized",
        "Practical",
        "Service-oriented",
        "Detail-focused"
      ],
      "strengths": [
        "Precision",
        "Planning",
        "Problem-solving"
      ],
      "weaknesses": [
        "Perfectionism",
        "Worry",
        "Overcritical nature"
      ]
    },
    {
      "id": "libra",
      "name": "Libra",
      "sanskritName": "Tula",
      "number": 7,
      "ruler": "Venus",
      "element": "Air",
      "modality": "Movable",
      "purushartha": "Kāma",
      "gender": "Odd (Masculine)",
      "nature": "Harmonious",
      "characteristics": [
        "Diplomatic",
        "Balanced",
        "Fair-minded",
        "Artistic",
        "Cooperative"
      ],
      "strengths": [
        "Negotiation",
        "Partnerships",
        "Sense of justice"
      ],
      "weaknesses": [
        "Indecisiveness",
        "Dependence on approval",
        "Avoidance of conflict"
      ]
    },
    {
      "id": "scorpio",
      "name": "Scorpio",
      "sanskritName": "Vrischika",
      "number": 8,
      "ruler": "Mars",
      "element": "Water",
      "modality": "Fixed",
      "purushartha": "Moksha",
      "gender": "Even (Feminine)",
      "nature": "Intense",
      "characteristics": [
        "Intense",
        "Determined",
        "Secretive",
        "Transformative",
        "Research-oriented"
      ],
      "strengths": [
        "Persistence",
        "Insight",
        "Emotional resilience"
      ],
      "weaknesses": [
        "Jealousy",
        "Suspicion",
        "Extremes of emotion"
      ]
    },
    {
      "id": "sagittarius",
      "name": "Sagittarius",
      "sanskritName": "Dhanu",
      "number": 9,
      "ruler": "Jupiter",
      "element": "Fire",
      "modality": "Dual",
      "purushartha": "Dharma",
      "gender": "Odd (Masculine)",
      "nature": "Philosophical",
      "characteristics": [
        "Wise",
        "Optimistic",
        "Philosophical",
        "Honest",
        "Spiritual"
      ],
      "strengths": [
        "Teaching",
        "Vision",
        "Faith"
      ],
      "weaknesses": [
        "Bluntness",
        "Overconfidence",
        "Dogmatism"
      ]
    },
    {
      "id": "capricorn",
      "name": "Capricorn",
      "sanskritName": "Makara",
      "number": 10,
      "ruler": "Saturn",
      "element": "Earth",
      "modality": "Movable",
      "purushartha": "Artha",
      "gender": "Even (Feminine)",
      "nature": "Practical",
      "characteristics": [
        "Disciplined",
        "Responsible",
        "Practical",
        "Ambitious",
        "Patient"
      ],
      "strengths": [
        "Organization",
        "Perseverance",
        "Leadership through effort"
      ],
      "weaknesses": [
        "Pessimism",
        "Rigidity",
        "Work-life imbalance"
      ]
    },
    {
      "id": "aquarius",
      "name": "Aquarius",
      "sanskritName": "Kumbha",
      "number": 11,
      "ruler": "Saturn",
      "element": "Air",
      "modality": "Fixed",
      "purushartha": "Kāma",
      "gender": "Odd (Masculine)",
      "nature": "Humanitarian",
      "characteristics": [
        "Independent",
        "Innovative",
        "Humanitarian",
        "Intellectual",
        "Community-oriented"
      ],
      "strengths": [
        "Original thinking",
        "Social vision",
        "Objectivity"
      ],
      "weaknesses": [
        "Emotional detachment",
        "Unpredictability",
        "Stubborn ideals"
      ]
    },
    {
      "id": "pisces",
      "name": "Pisces",
      "sanskritName": "Meena",
      "number": 12,
      "ruler": "Jupiter",
      "element": "Water",
      "modality": "Dual",
      "purushartha": "Moksha",
      "gender": "Even (Feminine)",
      "nature": "Spiritual",
      "characteristics": [
        "Compassionate",
        "Spiritual",
        "Intuitive",
        "Imaginative",
        "Charitable"
      ],
      "strengths": [
        "Empathy",
        "Devotion",
        "Creativity"
      ],
      "weaknesses": [
        "Escapism",
        "Confusion",
        "Difficulty setting boundaries"
      ]
    }
  ],
  "houses": [
    {
      "id": "house-1",
      "number": 1,
      "name": "1st House",
      "sanskritName": "Tanu Bhava",
      "primarySignifications": [
        "Self",
        "Body",
        "Personality"
      ],
      "represents": [
        "Physical body",
        "Appearance",
        "Personality",
        "Character",
        "Health",
        "Self-confidence",
        "Life direction",
        "Vitality"
      ],
      "questionsItAnswers": [
        "Who am I?",
        "How do others perceive me?"
      ],
      "naturalKarakas": [
        "Sun"
      ],
      "notes": [
        "Also influenced by the Ascendant Lord."
      ],
      "classifications": [
        "Kendra",
        "Trikona"
      ],
      "purushartha": "Dharma"
    },
    {
      "id": "house-2",
      "number": 2,
      "name": "2nd House",
      "sanskritName": "Dhana Bhava",
      "primarySignifications": [
        "Wealth",
        "Speech",
        "Family"
      ],
      "represents": [
        "Wealth",
        "Savings",
        "Family",
        "Speech",
        "Food habits",
        "Values",
        "Face",
        "Vision"
      ],
      "questionsItAnswers": [
        "What do I possess?",
        "How do I communicate?"
      ],
      "naturalKarakas": [
        "Jupiter (wealth)",
        "Venus (luxury)",
        "Mercury (speech)"
      ],
      "classifications": [
        "Panaphara"
      ],
      "purushartha": "Artha"
    },
    {
      "id": "house-3",
      "number": 3,
      "name": "3rd House",
      "sanskritName": "Sahaja Bhava",
      "primarySignifications": [
        "Courage",
        "Siblings",
        "Communication"
      ],
      "represents": [
        "Younger siblings",
        "Courage",
        "Initiative",
        "Writing",
        "Communication",
        "Skills",
        "Short journeys",
        "Arts",
        "Hands"
      ],
      "questionsItAnswers": [
        "How do I act?",
        "How do I communicate?"
      ],
      "naturalKarakas": [
        "Mars"
      ],
      "classifications": [
        "Upachaya",
        "Apoklima"
      ],
      "purushartha": "Kāma"
    },
    {
      "id": "house-4",
      "number": 4,
      "name": "4th House",
      "sanskritName": "Sukha Bhava",
      "primarySignifications": [
        "Mother",
        "Home",
        "Happiness"
      ],
      "represents": [
        "Mother",
        "Home",
        "Property",
        "Vehicles",
        "Education",
        "Emotional happiness",
        "Inner peace",
        "Real estate"
      ],
      "questionsItAnswers": [
        "Where is my emotional security?"
      ],
      "naturalKarakas": [
        "Moon",
        "Venus"
      ],
      "classifications": [
        "Kendra"
      ],
      "purushartha": "Moksha"
    },
    {
      "id": "house-5",
      "number": 5,
      "name": "5th House",
      "sanskritName": "Putra Bhava",
      "primarySignifications": [
        "Children",
        "Intelligence",
        "Mantra"
      ],
      "represents": [
        "Children",
        "Intelligence",
        "Creativity",
        "Education",
        "Purva Punya",
        "Mantras",
        "Romance",
        "Speculation"
      ],
      "questionsItAnswers": [
        "What do I create?"
      ],
      "naturalKarakas": [
        "Jupiter"
      ],
      "classifications": [
        "Trikona",
        "Panaphara"
      ],
      "purushartha": "Dharma"
    },
    {
      "id": "house-6",
      "number": 6,
      "name": "6th House",
      "sanskritName": "Ari Bhava",
      "primarySignifications": [
        "Enemies",
        "Disease",
        "Service"
      ],
      "represents": [
        "Disease",
        "Debts",
        "Enemies",
        "Competition",
        "Litigation",
        "Service",
        "Discipline",
        "Daily work"
      ],
      "questionsItAnswers": [
        "What challenges must I overcome?"
      ],
      "naturalKarakas": [
        "Mars",
        "Saturn"
      ],
      "classifications": [
        "Upachaya",
        "Dusthana",
        "Apoklima"
      ],
      "purushartha": "Artha"
    },
    {
      "id": "house-7",
      "number": 7,
      "name": "7th House",
      "sanskritName": "Yuvati Bhava",
      "primarySignifications": [
        "Marriage",
        "Partnerships"
      ],
      "represents": [
        "Marriage",
        "Spouse",
        "Partnerships",
        "Contracts",
        "Public dealings",
        "Business partnerships",
        "Foreign residence (in some contexts)"
      ],
      "questionsItAnswers": [
        "How do I relate to others?"
      ],
      "naturalKarakas": [
        "Venus"
      ],
      "classifications": [
        "Kendra"
      ],
      "purushartha": "Kāma"
    },
    {
      "id": "house-8",
      "number": 8,
      "name": "8th House",
      "sanskritName": "Randhra Bhava",
      "primarySignifications": [
        "Longevity",
        "Transformation"
      ],
      "represents": [
        "Longevity",
        "Sudden events",
        "Transformation",
        "Inheritance",
        "Occult sciences",
        "Mysticism",
        "Hidden knowledge",
        "Research"
      ],
      "questionsItAnswers": [
        "How do I transform?"
      ],
      "naturalKarakas": [
        "Saturn",
        "Ketu"
      ],
      "classifications": [
        "Dusthana",
        "Panaphara"
      ],
      "purushartha": "Moksha"
    },
    {
      "id": "house-9",
      "number": 9,
      "name": "9th House",
      "sanskritName": "Dharma Bhava",
      "primarySignifications": [
        "Fortune",
        "Guru",
        "Father",
        "Religion"
      ],
      "represents": [
        "Fortune",
        "Dharma",
        "Guru",
        "Higher education",
        "Pilgrimage",
        "Religion",
        "Philosophy",
        "Father",
        "Blessings"
      ],
      "questionsItAnswers": [
        "What gives my life meaning?"
      ],
      "naturalKarakas": [
        "Jupiter",
        "Sun (father)"
      ],
      "classifications": [
        "Trikona",
        "Apoklima"
      ],
      "purushartha": "Dharma"
    },
    {
      "id": "house-10",
      "number": 10,
      "name": "10th House",
      "sanskritName": "Karma Bhava",
      "primarySignifications": [
        "Profession",
        "Status",
        "Actions"
      ],
      "represents": [
        "Career",
        "Profession",
        "Status",
        "Public image",
        "Reputation",
        "Authority",
        "Actions",
        "Responsibility"
      ],
      "questionsItAnswers": [
        "What is my contribution to society?"
      ],
      "naturalKarakas": [
        "Sun",
        "Mercury",
        "Saturn",
        "Jupiter (depending on profession)"
      ],
      "classifications": [
        "Kendra",
        "Upachaya"
      ],
      "purushartha": "Artha"
    },
    {
      "id": "house-11",
      "number": 11,
      "name": "11th House",
      "sanskritName": "Labha Bhava",
      "primarySignifications": [
        "Gains",
        "Friends",
        "Ambitions"
      ],
      "represents": [
        "Gains",
        "Income",
        "Friends",
        "Networks",
        "Elder siblings",
        "Recognition",
        "Ambitions",
        "Fulfillment of desires"
      ],
      "questionsItAnswers": [
        "What do I achieve?"
      ],
      "naturalKarakas": [
        "Jupiter"
      ],
      "classifications": [
        "Upachaya",
        "Panaphara"
      ],
      "purushartha": "Kāma"
    },
    {
      "id": "house-12",
      "number": 12,
      "name": "12th House",
      "sanskritName": "Vyaya Bhava",
      "primarySignifications": [
        "Loss",
        "Expenses",
        "Liberation"
      ],
      "represents": [
        "Expenses",
        "Losses",
        "Charity",
        "Foreign lands",
        "Meditation",
        "Sleep",
        "Hospitals",
        "Ashrams",
        "Liberation (Moksha)"
      ],
      "questionsItAnswers": [
        "What must I let go of?"
      ],
      "naturalKarakas": [
        "Saturn",
        "Ketu"
      ],
      "classifications": [
        "Dusthana",
        "Apoklima"
      ],
      "purushartha": "Moksha"
    }
  ],
  "concepts": [
    {
      "id": "graha-overview",
      "title": "What are Naisargika Kārakatvas?",
      "category": "planets",
      "intro": "In Vedic astrology (Jyotiṣa), every planet (Graha) has natural significations called Naisargika Kārakatvas. These represent what the planet naturally signifies regardless of the ascendant. Both Parāśara and Jaimini astrology rely on these significations, although Jaimini also assigns Chara Kārakas (variable significators) based on planetary degrees.",
      "blocks": [
        {
          "type": "table",
          "title": "One-word Essence of Each Planet",
          "headers": [
            "Planet",
            "One-word Essence"
          ],
          "rows": [
            [
              "Sun",
              "Authority"
            ],
            [
              "Moon",
              "Mind"
            ],
            [
              "Mars",
              "Action"
            ],
            [
              "Mercury",
              "Intellect"
            ],
            [
              "Jupiter",
              "Wisdom"
            ],
            [
              "Venus",
              "Love"
            ],
            [
              "Saturn",
              "Discipline"
            ],
            [
              "Rahu",
              "Ambition"
            ],
            [
              "Ketu",
              "Liberation"
            ]
          ]
        }
      ]
    },
    {
      "id": "chara-karakas",
      "title": "Chara Kārakas (Jaimini Astrology)",
      "category": "planets",
      "intro": "Jaimini adds another layer through Chara Kārakas, where planets take on roles based on their celestial longitude in a given chart.",
      "blocks": [
        {
          "type": "table",
          "headers": [
            "Chara Kāraka",
            "Signifies"
          ],
          "rows": [
            [
              "Atmakaraka",
              "Soul, life's lessons"
            ],
            [
              "Amatyakaraka",
              "Career, vocation"
            ],
            [
              "Bhratrukaraka",
              "Siblings, courage"
            ],
            [
              "Matrukaraka",
              "Mother"
            ],
            [
              "Putrakaraka",
              "Children, creativity"
            ],
            [
              "Gnatikaraka",
              "Relatives, obstacles, conflicts"
            ],
            [
              "Darakaraka",
              "Spouse and partnerships"
            ],
            [
              "Pitrukaraka (in the 8-karaka system)",
              "Father, lineage"
            ]
          ]
        },
        {
          "type": "text",
          "text": "These Chara Kārakas do not replace the natural significations. For instance, the Sun naturally signifies the father, but if Saturn becomes the Pitrukaraka in a particular chart, Saturn also carries the father's role in Jaimini analysis."
        }
      ]
    },
    {
      "id": "naisargika-maitri",
      "title": "Naisargika Maitri — Natural Planetary Friendships",
      "category": "planets",
      "intro": "In the Parāśara system, Naisargika Maitri is the permanent friendship, enmity, or neutrality between planets — independent of their placement in any horoscope. It applies to the seven classical grahas; Rāhu and Ketu are generally not included in the classical table.",
      "blocks": [
        {
          "type": "table",
          "title": "Naisargika Relationship Chart (Parāśara)",
          "headers": [
            "Planet",
            "Friends",
            "Enemies",
            "Neutrals"
          ],
          "rows": [
            [
              "Sun (Ravi)",
              "Moon, Mars, Jupiter",
              "Venus, Saturn",
              "Mercury"
            ],
            [
              "Moon (Chandra)",
              "Sun, Mercury",
              "None",
              "Mars, Jupiter, Venus, Saturn"
            ],
            [
              "Mars (Kuja)",
              "Sun, Moon, Jupiter",
              "Mercury",
              "Venus, Saturn"
            ],
            [
              "Mercury (Budha)",
              "Sun, Venus",
              "Moon",
              "Mars, Jupiter, Saturn"
            ],
            [
              "Jupiter (Guru)",
              "Sun, Moon, Mars",
              "Mercury, Venus",
              "Saturn"
            ],
            [
              "Venus (Śukra)",
              "Mercury, Saturn",
              "Sun, Moon",
              "Mars, Jupiter"
            ],
            [
              "Saturn (Śani)",
              "Mercury, Venus",
              "Sun, Moon, Mars",
              "Jupiter"
            ]
          ]
        },
        {
          "type": "steps",
          "title": "How to use this table",
          "items": [
            "Planet in a friend's sign — the planet gets support. Example: Jupiter in Cancer (the Moon's sign) is supported because the Moon is Jupiter's natural friend.",
            "Planet in an enemy's sign — the planet's expression becomes less comfortable. Example: Jupiter in Gemini (Mercury's sign), because Mercury is Jupiter's natural enemy.",
            "Planet in a neutral sign — the planet gives moderate results."
          ]
        },
        {
          "type": "text",
          "title": "Important Parāśara point: temporary + natural relationship",
          "text": "For accurate judgment, Parāśara combines Naisargika Maitri (natural relationship) with Tatkālika Maitri (temporary relationship based on house positions). Together they form the Pañcadhā Maitri — the five-fold friendship."
        },
        {
          "type": "table",
          "title": "Pañcadhā Maitri (Five-fold Friendship)",
          "headers": [
            "Combined Relationship",
            "Result"
          ],
          "rows": [
            [
              "Great Friend",
              "Excellent support"
            ],
            [
              "Friend",
              "Good support"
            ],
            [
              "Neutral",
              "Average"
            ],
            [
              "Enemy",
              "Difficulty"
            ],
            [
              "Great Enemy",
              "Strong obstruction"
            ]
          ]
        },
        {
          "type": "text",
          "title": "Example: Jupiter in Sagittarius",
          "text": "Jupiter in Sagittarius is in its own sign — maximum dignity. If the Sun is conjunct Jupiter, Jupiter receives support, because the Sun is Jupiter's natural friend. Mars aspecting Jupiter also supports, since Mars is a natural friend. Mercury conjunct Jupiter introduces some tension, because Mercury is Jupiter's natural enemy. Saturn conjunct Jupiter is neutral to Jupiter. This kind of combined reading — dignity, conjunctions, and aspects weighed together — is what Parāśara recommends, rather than judging one factor alone."
        }
      ]
    },
    {
      "id": "sign-classifications",
      "title": "Classical Sign Classifications",
      "category": "signs",
      "intro": "Besides their individual characteristics, each sign belongs to several traditional groups.",
      "blocks": [
        {
          "type": "table",
          "headers": [
            "Classification",
            "Signs"
          ],
          "rows": [
            [
              "Fire (Agni)",
              "Aries, Leo, Sagittarius"
            ],
            [
              "Earth (Bhūmi)",
              "Taurus, Virgo, Capricorn"
            ],
            [
              "Air (Vāyu)",
              "Gemini, Libra, Aquarius"
            ],
            [
              "Water (Jala)",
              "Cancer, Scorpio, Pisces"
            ],
            [
              "Movable (Chara)",
              "Aries, Cancer, Libra, Capricorn"
            ],
            [
              "Fixed (Sthira)",
              "Taurus, Leo, Scorpio, Aquarius"
            ],
            [
              "Dual (Dwisvabhāva)",
              "Gemini, Virgo, Sagittarius, Pisces"
            ],
            [
              "Dharma",
              "Aries, Leo, Sagittarius"
            ],
            [
              "Artha",
              "Taurus, Virgo, Capricorn"
            ],
            [
              "Kāma",
              "Gemini, Libra, Aquarius"
            ],
            [
              "Moksha",
              "Cancer, Scorpio, Pisces"
            ],
            [
              "Odd (Oja/Masculine)",
              "Aries, Gemini, Leo, Libra, Sagittarius, Aquarius"
            ],
            [
              "Even (Yugma/Feminine)",
              "Taurus, Cancer, Virgo, Scorpio, Capricorn, Pisces"
            ]
          ]
        }
      ]
    },
    {
      "id": "interpreting-a-rasi",
      "title": "How to Interpret a Rāśi",
      "category": "signs",
      "intro": "When analyzing any sign in a horoscope, consider it in layers:",
      "blocks": [
        {
          "type": "steps",
          "items": [
            "Ruling planet — Who governs the sign?",
            "Element (Tattva) — How does it express energy?",
            "Modality — Does it initiate, stabilize, or adapt?",
            "Purushartha — What is its life aim (Dharma, Artha, Kāma, Moksha)?",
            "Gender (Oja/Yugma) — Is its expression active or receptive?",
            "Natural temperament — What are its inherent strengths and challenges?"
          ]
        },
        {
          "type": "text",
          "title": "Example: Leo",
          "text": "Leo is ruled by the Sun (authority and vitality), a Fire sign (dynamic expression), Fixed (steadfast), Dharma-oriented (purpose and righteousness), Odd/Masculine (active), and naturally inclined toward leadership and responsibility."
        },
        {
          "type": "text",
          "text": "This layered approach provides a much richer understanding than looking at the sign alone and is the method traditionally used in both Parāśara and Jaimini astrology."
        }
      ]
    },
    {
      "id": "house-classifications",
      "title": "House Classifications",
      "category": "houses",
      "intro": "The twelve houses are grouped into several classical categories.",
      "blocks": [
        {
          "type": "list",
          "title": "1. Kendras (Angular Houses) — 1, 4, 7, 10",
          "items": [
            "Strength",
            "Stability",
            "Action",
            "Foundation of life"
          ],
          "text": "Strong planets in Kendras often become influential."
        },
        {
          "type": "list",
          "title": "2. Trikonas (Trinal Houses) — 1, 5, 9",
          "items": [
            "Dharma",
            "Fortune",
            "Intelligence",
            "Blessings",
            "Spiritual merit"
          ],
          "text": "The combination of Kendra and Trikona lords is the basis for many Rāja Yogas in Parāśara."
        },
        {
          "type": "list",
          "title": "3. Upachayas (Growth Houses) — 3, 6, 10, 11",
          "items": [
            "Improvement over time",
            "Effort",
            "Competition",
            "Achievement"
          ],
          "text": "Malefic planets (Mars, Saturn, Rahu) often perform well in these houses because they support persistence and overcoming obstacles."
        },
        {
          "type": "list",
          "title": "4. Dusthanas (Difficult Houses) — 6, 8, 12",
          "items": [
            "Obstacles",
            "Disease",
            "Debts",
            "Loss",
            "Transformation",
            "Spiritual growth through challenges"
          ],
          "text": "Although considered difficult, these houses can also foster resilience, healing, and spiritual development."
        },
        {
          "type": "list",
          "title": "5. Panaphara Houses (Succedent) — 2, 5, 8, 11",
          "items": [],
          "text": "Associated with sustaining and developing what has been initiated."
        },
        {
          "type": "list",
          "title": "6. Apoklima Houses (Cadent) — 3, 6, 9, 12",
          "items": [],
          "text": "Associated with movement, learning, transition, and adaptation."
        }
      ]
    },
    {
      "id": "houses-purusharthas",
      "title": "Houses and the Four Purusharthas",
      "category": "houses",
      "blocks": [
        {
          "type": "table",
          "headers": [
            "Purushartha",
            "Houses",
            "Meaning"
          ],
          "rows": [
            [
              "Dharma",
              "1, 5, 9",
              "Identity, purpose, higher principles"
            ],
            [
              "Artha",
              "2, 6, 10",
              "Resources, work, achievement"
            ],
            [
              "Kāma",
              "3, 7, 11",
              "Desires, relationships, aspirations"
            ],
            [
              "Moksha",
              "4, 8, 12",
              "Inner peace, transformation, liberation"
            ]
          ]
        },
        {
          "type": "text",
          "text": "This pattern mirrors the Purushartha grouping of the zodiac signs and is a key organizing principle in Vedic astrology."
        }
      ]
    },
    {
      "id": "houses-jaimini",
      "title": "Houses in Jaimini Astrology",
      "category": "houses",
      "intro": "Jaimini astrology uses the houses somewhat differently from Parāśara:",
      "blocks": [
        {
          "type": "list",
          "items": [
            "Rāśis (signs) are often treated as primary, with Rāśi dṛṣṭi (sign aspects) playing a major role.",
            "Chara Karakas assign life roles (such as spouse, children, or career) to planets based on their longitude.",
            "Karakamsha Lagna (the Navamsa sign occupied by the Atmakaraka, projected into the birth chart) becomes a special reference point for spiritual and vocational analysis.",
            "Arudha Padas reveal how the affairs of a house are perceived or manifest in the external world.",
            "House results are interpreted together with the house lord, occupying planets, aspects, strength, and relevant dashas."
          ]
        }
      ]
    },
    {
      "id": "who-how-where",
      "title": "The Big Picture: Who, How, Where",
      "category": "general",
      "intro": "You can think of a horoscope in this way:",
      "blocks": [
        {
          "type": "list",
          "items": [
            "Planets (Grahas) = Who is acting (the actors or agents).",
            "Signs (Rāśis) = How they act (their style, temperament, and motivation).",
            "Houses (Bhāvas) = Where they act (the area of life affected)."
          ]
        },
        {
          "type": "text",
          "title": "Example: Mars in Capricorn in the 10th house",
          "text": "Mars brings action, courage, initiative. Capricorn gives a disciplined, practical, goal-oriented expression. The 10th house is career, profession, public reputation. Together, this combination often indicates someone who channels energy into disciplined professional achievement and leadership."
        },
        {
          "type": "text",
          "text": "The final interpretation, however, always depends on the complete chart, including planetary dignity, aspects, yogas, and dashas."
        }
      ]
    }
  ]
};
